"""add_floorplan_analysis

Revision ID: 487e50664725
Revises: activity_logs_20260202
Create Date: 2026-02-02 22:46:57.460599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487e50664725'
down_revision: Union[str, Sequence[str], None] = 'activity_logs_20260202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floorplan_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floorplan_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.Enum('MATERIAL', 'THERMAL', 'VISUAL', name='analysistype'), nullable=False),
    sa.Column('modelUsed', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['floorplan_id'], ['floorplans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floorplan_analysis_id'), 'floorplan_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floorplan_analysis_id'), table_name='floorplan_analysis')
    op.drop_table('floorplan_analysis')
    # ### end Alembic commands ###
