"""Add new column to projects table

Revision ID: fba505825e8a
Revises: e97113213839
Create Date: 2026-04-14 22:03:49.945514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fba505825e8a'
down_revision: Union[str, Sequence[str], None] = 'e97113213839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_access_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='requeststatus'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='requestaccess', native_enum=False),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::requeststatus"))
    op.alter_column('project_access_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_access_requests', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_project_access_requests_id'), 'project_access_requests', ['id'], unique=False)
    op.alter_column('project_collaborators', 'role',
               existing_type=postgresql.ENUM('OWNER', 'COLLABORATOR', name='projectrole'),
               nullable=True,
               existing_server_default=sa.text("'COLLABORATOR'::projectrole"))
    op.alter_column('project_collaborators', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_project_collaborators_id'), 'project_collaborators', ['id'], unique=False)
    op.add_column('projects', sa.Column('north_arrow_direction', sa.String(), nullable=False, server_default='N'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'north_arrow_direction')
    op.drop_index(op.f('ix_project_collaborators_id'), table_name='project_collaborators')
    op.alter_column('project_collaborators', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_collaborators', 'role',
               existing_type=postgresql.ENUM('OWNER', 'COLLABORATOR', name='projectrole'),
               nullable=False,
               existing_server_default=sa.text("'COLLABORATOR'::projectrole"))
    op.drop_index(op.f('ix_project_access_requests_id'), table_name='project_access_requests')
    op.alter_column('project_access_requests', 'responded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('project_access_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_access_requests', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='requestaccess', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='requeststatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::requeststatus"))
    # ### end Alembic commands ###
